davea42/libdwarf-code

- .gitignore
'git status' reports files generated with configure or make. This commit removes them from the status report.
> ignore more autotools files

- src/lib/libdwarf/Makefile.am
- src/lib/libdwarf/libdwarf.h
This allow less collision symbols, detect errors,
optimisations during link, etc..
On Windows, here are some numbers :
Libraries both compiled with -O2
without DW_API : 584815 bytes
with DW_API :    578671 bytes
1.05% gain (size)
after stripping :
without DW_API : 453120 bytes 506 symbols
with DW_API :    446976 bytes 338 symbols
1.35% gain (size)
modified:   src/lib/libdwarf/Makefile.am
modified:   src/lib/libdwarf/libdwarf.h
> Add DW_API to explicitly set public symbols

- src/lib/libdwarf/dwarf_debuglink.c
modified:   src/lib/libdwarf/dwarf_debuglink.c
> Include direct.h on Windows to declare getcwd()

- CMakeLists.txt
- cmake/config.h.cmake
- configure.ac
- src/bin/dwarfdump/print_die.c
- src/bin/dwarfdump/print_macro.c
- src/lib/libdwarfp/dwarf_pro_arange.c
- src/lib/libdwarfp/dwarf_pro_dnames.c
- src/lib/libdwarfp/dwarf_pro_funcs.c
- src/lib/libdwarfp/dwarf_pro_pubnames.c
- src/lib/libdwarfp/dwarf_pro_reloc_stream.c
- src/lib/libdwarfp/dwarf_pro_reloc_symbolic.c
- src/lib/libdwarfp/dwarf_pro_section.c
- src/lib/libdwarfp/dwarf_pro_types.c
- src/lib/libdwarfp/dwarf_pro_vars.c
- src/lib/libdwarfp/dwarf_pro_weaks.c
modified:   src/bin/dwarfdump/print_die.c
modified:   src/bin/dwarfdump/print_macro.c
Remove useless elfaccess.h header file
modified:   CMakeLists.txt
modified:   cmake/config.h.cmake
modified:   configure.ac
modified:   src/lib/libdwarfp/dwarf_pro_arange.c
modified:   src/lib/libdwarfp/dwarf_pro_dnames.c
modified:   src/lib/libdwarfp/dwarf_pro_funcs.c
modified:   src/lib/libdwarfp/dwarf_pro_pubnames.c
modified:   src/lib/libdwarfp/dwarf_pro_reloc_stream.c
modified:   src/lib/libdwarfp/dwarf_pro_reloc_symbolic.c
modified:   src/lib/libdwarfp/dwarf_pro_section.c
modified:   src/lib/libdwarfp/dwarf_pro_types.c
modified:   src/lib/libdwarfp/dwarf_pro_vars.c
modified:   src/lib/libdwarfp/dwarf_pro_weaks.c
> Fix "function declaration isn't a prototype" warning 

- src/bin/dwarfdump/print_die.c
- src/bin/dwarfdump/print_macro.c
modified:   src/bin/dwarfdump/print_die.c
modified:   src/bin/dwarfdump/print_macro.c
> Fix "function declaration isn't a prototype" warning

- src/bin/dwarfdump/print_ranges.c
dwarfdump
modified:   ../src/bin/dwarfdump/print_ranges.c
> Fix one more "function declaration isn't a prototype" warning in

- test/meson.build
- test/test_linkedtopath.c
- test/test_regex.c
modified:   test/meson.build
modified:   test/test_linkedtopath.c
modified:   test/test_regex.c
> fix tests compilation with meson

- src/lib/libdwarf/dwarf_peread.c
Removed in-memory size check, and replaced in with in-file size check.
Checking in-memory section size can trigger false positive result with large .bss sections.
> Replacing Windows PE section size sanity check.

- src/bin/dwarfdump/dd_esb.c
- src/bin/dwarfdump/dd_macrocheck.c
- test/CMakeLists.txt
- test/Makefile.am
- test/meson.build
autotools on Windows
modified:   src/bin/dwarfdump/dd_esb.c
modified:   src/bin/dwarfdump/dd_macrocheck.c
modified:   test/CMakeLists.txt
modified:   test/Makefile.am
modified:   test/meson.build
> Rename SELFTEST with TESTING. Also fix compilation of tests with the

- test/dwarf_leb_test.c
- test/dwarf_tied_test.c
- test/getnametest.c
- test/helpertree_test.c
- test/makename_test.c
- test/section_bitmaps_test.c
- test/test_canonical.c
- test/test_dwarfstring.c
- test/test_errmsglist.c
- test/test_extra_flag_strings.c
- test/test_linkedtopath.c
- test/test_regex.c
- test/test_safe_strcpy.c
- test/testesb.c
modified:   test/dwarf_leb_test.c
modified:   test/dwarf_tied_test.c
modified:   test/getnametest.c
modified:   test/helpertree_test.c
modified:   test/makename_test.c
modified:   test/section_bitmaps_test.c
modified:   test/test_canonical.c
modified:   test/test_dwarfstring.c
modified:   test/test_errmsglist.c
modified:   test/test_extra_flag_strings.c
modified:   test/test_linkedtopath.c
modified:   test/test_regex.c
modified:   test/test_safe_strcpy.c
modified:   test/testesb.c
> tests: reorganize headers

- src/lib/libdwarf/dwarf_line.c
This patch resolves the following undefined behavior error:
"runtime error: applying zero offset to null pointer" seen when
calling dwarf_srclines_b when compiled with clang's UBSAN libraries.
> Fix undefined behavior found when compiled with UBSAN in clang.

- meson.build
> Remove useless warnings about "non standard function names" from the

- CMakeLists.txt
- src/bin/dwarfdump/CMakeLists.txt
- src/bin/dwarfexample/CMakeLists.txt
- src/bin/dwarfgen/CMakeLists.txt
- src/lib/libdwarf/CMakeLists.txt
- src/lib/libdwarfp/CMakeLists.txt
- test/CMakeLists.txt
Replacing CMAKE_*_DIR with PROJECT_*_DIR allows adding this project as a subproject in cmake config.
> Replace CMAKE dirs with PROJECT dirs

- CMakeLists.txt
check_c_source_runs cannot be run in crosscompilation cases, only check compilation by replacing it with `check_c_source_compiles`
Fixes #149
> CMakeLists: fix crosscompile cmake build

- fuzz/fuzz_dnames.c
Since `dwarf_dnames_abbrev_by_code` and `dwarf_dnames_abbrev_form_by_index` are deprecated, this fix will make the related fuzzer build again.
> Remove deprecated functions from the fuzzer source

- src/lib/libdwarf/dwarf_elf_load_headers.c
Hi,
`e_strndx` doesn't necessarily need to be big (`>=SHN_LORESERVE`) in tandem with big `e_shnum` (set to 0). Currently I have valid example that looks like this:
`e_shnum == 0` (where in section header at index 0, `sh_size == 100000`)
`e_strndx == 1`
Setting `e_shnum == 0` is enough to indicate that there is big number of sections. There is two quotation in ELF spec:
- https://refspecs.linuxfoundation.org/elf/gabi4+/ch4.sheader.html
> "[...] If the **number of sections is greater than or equal to SHN_LORESERVE (0xff00), e_shnum has the value SHN_UNDEF (0)** and the actual number of section header table entries is contained in the sh_size field of the section header at index 0 (otherwise, the sh_size member of the initial entry contains 0)."
- …
> Support for large number of section headers

- src/lib/libdwarf/dwarf.h
DW_AT_GNU_bias is duplicated. Same entry in line 634 (632).
> DW_AT_GNU_bias duplicate removed

- src/lib/libdwarf/dwarf_frame.c
- src/lib/libdwarf/libdwarf.h
In order to make it easy to iterate through all rows for a given FDE, I've added `dwarf_get_fde_info_for_all_regs3_b`.
The new function outputs the subsequent PC and whether there are more rows available, which allows for easy iteration without having to keep adding 1 to the input PC to go through all rows. This is similar to what other, existing, functions like `dwarf_get_fde_info_for_reg3_c` also do. It's a minor change that mostly just means passing on the two new output parameters verbatim  to `_dwarf_get_fde_info_for_a_pc_row` that's used internally (and already had this support).
The old `dwarf_get_fde_info_for_all_regs3` still exists, but now just calls the new function internally, so this shouldn't break anything.
> Added dwarf_get_fde_info_for_all_regs3_b

- src/bin/dwarfdump/print_die.c
DW_AT_data_bit_offset is not handled in get_attr_value() which cause dwarfdump output negative value of DW_AT_data_bit_offset attribute.
A simple test source code:
```c
#include <stdio.h>
struct struct_A {
void            *p0;
void            *p1;
int             a: 1;
int             b: 1;
unsigned        c;
} a = {
.p0 = NULL,
.p1 = NULL,
.a = 1,
.b = 1,
.c = 7,
};
int main(int argc, char *argv[])
{
return 0;
}
```
Before patch:
```
< 2><0x00000097>      DW_TAG_member
DW_AT_name                  a
DW_AT_decl_file             0x00000001
DW_AT_decl_line             0x00000007
DW_AT_decl_column           0x00000019
DW_AT_type                  <0x0000005a>
DW_AT_bit_size              0x00000001
DW_AT_data_bit_offset       -128
< 2><0x000000a0>      DW_TAG_member
DW_AT_name …
```
> handle DW_AT_data_bit_offset in get_attr_value()

- src/lib/libdwarf/dwarf_elf_load_headers.c
- src/lib/libdwarf/dwarf_generic_init.c
- src/lib/libdwarf/dwarf_object_detector.c
This PR addresses a build failure on mingw noticed by @yannou38 in https://github.com/jeremy-rifkin/cpptrace/issues/66. On some mingw installations fcntl.h may be missing. Some files I've looked at here do `#ifndef O_RDONLY #define O_RDONLY 0` as a substitute so I've applied that to other files using O_RDONLY.
> Add ifndef-define for O_RDONLY in elf_load_headers and generic_init

- CMakeLists.txt
Currently, the only way to disable these is to uninstall one of them from the system, which is not very convenient 😄 
I'm happy to iterate on the option' name/description if this patch makes sense 🙌
> Add a CMake option to disable libz/libzstd

- meson.build
- src/bin/dwarfdump/meson.build
- src/bin/dwarfgen/meson.build
- src/lib/libdwarf/meson.build
- src/lib/libdwarfp/meson.build
Allows use as a wrap subproject more cleanly. There is no effect by the added statements if libdwarf is not built as a subproject.
> override find_program/dependency in meson scripts

- meson.build
- test/meson.build
the config file needs to be copied over. this adds that.
> make dwarfdump tests work under Meson

- src/bin/dwarfgen/createirepformfrombinary.cc
- src/lib/libdwarf/libdwarf_private.h
There still exist numerous warnings about conversion (C4267, C4244), but this makes it compile if /WX is off.
> Minor fixes for compatibility with MSVC.

- meson.build
Under MSVC, `/WX` (the equivalent to `-Werror`) will cause the build to crash and burn. This makes it not default to making the build crash and burn.
> Disable default werror=true in Meson manifest

- src/bin/dwarfdump/dd_tsearchbal.c
- src/bin/dwarfdump/print_debug_names.c
- src/lib/libdwarf/dwarf_frame.c
- src/lib/libdwarf/dwarf_harmless.c
- src/lib/libdwarf/dwarf_machoread.c
- src/lib/libdwarf/dwarf_ranges.c
- src/lib/libdwarf/dwarf_tsearchhash.c
This fixes warnings about wrong order of calloc arguments
modified:   src/bin/dwarfdump/dd_tsearchbal.c
modified:   src/bin/dwarfdump/print_debug_names.c
modified:   src/lib/libdwarf/dwarf_frame.c
modified:   src/lib/libdwarf/dwarf_harmless.c
modified:   src/lib/libdwarf/dwarf_machoread.c
modified:   src/lib/libdwarf/dwarf_ranges.c
modified:   src/lib/libdwarf/dwarf_tsearchhash.c
> build: fix arguments order in calloc calls

- src/lib/libdwarf/CMakeLists.txt
I got an issue on my library cpptrace about specifying an export set in cmake https://github.com/jeremy-rifkin/cpptrace/issues/189. It looks like it's important to both `install(EXPORT)` and `export()` in cmake.
In order to patch this in my repository, it looks like libdwarf needs to define an export set too. This PR implements this. Tested locally and things seem ok.
> Specify a cmake export set

- src/lib/libdwarf/meson.build
- src/lib/libdwarfp/meson.build
I tried to use static build of libdwarf as a meson subproject, but it seems `LIBDWARF_STATIC` is not defined when using it and I got link errors. Adding the compile flag to `declare_dependency()` fixed the issue.
> Add LIBDWARF_STATIC macro to static libdwarf dependency on meson

- CMakeLists.txt
Cmake is now warning about compatibility with versions `< 3.10 ` being dropped. This PR just bumps the minimum version. 
https://cliutils.gitlab.io/modern-cmake/chapters/intro/installing.html#full-list suggests that 3.10 is widely available, only very old linux distros shipped older versions (like ubuntu 16 or centos 7)
Zstd recently set its minimum version to 3.10 as well https://github.com/facebook/zstd/blob/f8745da6ff1ad1e7bab384bd1f9d742439278e99/build/cmake/CMakeLists.txt#L10.
Closes #277
> Bump cmake minimum version to 3.10

- CMakeLists.txt
As mentioned in the command CMake already deals with this. Worse adding this ourself could create some trouble for people using this repo with add_subdirectory or FetchContent etc...
> Suppress FIND_LIBRARY_USE_LIB64_PATHS

- src/lib/libdwarfp/Makefile.am
autoconf build was failing to build when trying to build `libdwarfp`
See https://github.com/davea42/libdwarf-code/issues/294 for full build log failure.
I updated [src/lib/libdwarfp/Makefile.am](https://github.com/davea42/libdwarf-code/compare/main...zwilcox:libdwarf-code:make_libdwarfp_build?expand=1#diff-09d99fe8c82fef37dd6147556e0b61497e83210fab65642c84387b136cf50404) to build dependencies.
See full build log below:
```
make -j$(nproc)
make  all-recursive
make[1]: Entering directory '/home/heat_/zbwilco-libdwarf'
Making all in src/lib/libdwarf
make[2]: Entering directory '/home/heat_/zbwilco-libdwarf/src/lib/libdwarf'
CC       libdwarf_la-dwarf_abbrev.lo
CC       libdwarf_la-dwarf_alloc.lo
CC       libdwarf_la-dwarf_arange.lo
CC       libdwarf_la-dwarf_crc.lo
CC …
```
> meson build when trying to build libdwarfp.  Updating Makefile.am
