src/bin/dwarfdump/dwconf.c
Fallback to Unix code if still not found
=> dwarfdump: move dwarfdump.comp detection on Windows outside the loop

configure.ac
=> Replace C comments in configure.ac with valid comment

src/lib/libdwarfp/Makefile.am, src/lib/libdwarfp/libdwarfp.h
modified:   src/lib/libdwarfp/Makefile.am
modified:   src/lib/libdwarfp/libdwarfp.h
=> The API macro in libdwarfp must different from the one in libwarf on Windows

.gitignore
=> ignore libdwarfp.pc and a conf file in test/

README.md
=> Use markdown features for README.md

CMakeLists.txt, cmake/config.h.cmake, configure.ac, src/lib/libdwarfp/dwarf_pro_incl.h
modified:   CMakeLists.txt
modified:   cmake/config.h.cmake
modified:   configure.ac
modified:   src/lib/libdwarfp/dwarf_pro_incl.h
=> remove checks of useless header files

meson.build, src/bin/attr_form/attr_form_build.c, src/bin/attr_form/meson.build, src/bin/tag_attr/meson.build, src/bin/tag_attr/tag_attr.c, src/bin/tag_tree/meson.build, src/bin/tag_tree/tag_tree.c
also clean header files order
new file:   src/bin/attr_form/meson.build
new file:   src/bin/tag_attr/meson.build
new file:   src/bin/tag_tree/meson.build
modified:   src/bin/attr_form/attr_form_build.c
modified:   src/bin/tag_attr/tag_attr.c
modified:   src/bin/tag_tree/tag_tree.c
=> Add meson build for attr_form, tag_attr and tag_tree binaries

README.md, meson.build, src/bin/buildopstab/buildopscounttab.c, src/bin/buildopstab/meson.build, src/bin/builduritable/meson.build, src/bin/builduritable/uritablebuild.c, src/bin/gennames/gennames.c, src/bin/gennames/meson.build
new file:   src/bin/buildopstab/meson.build
new file:   src/bin/builduritable/meson.build
new file:   src/bin/gennames/meson.build
modified:   README.md
modified:   src/bin/buildopstab/buildopscounttab.c
modified:   src/bin/builduritable/uritablebuild.c
modified:   src/bin/gennames/gennames.c
=> Add meson support for the last binaries

doc/meson.build, meson.build
=> install man pages

configure.ac, doc/Makefile.am, doc/meson.build, meson.build, meson_options.txt
modified:   configure.ac
modified:   doc/Makefile.am
modified:   doc/meson.build
modified:   meson_options.txt
=> Add Doxygen support for autotools and meson

meson.build, test/dwarf_tied_test.c, test/getnametest.c, test/getopttest.c, test/helpertree_test.c, test/makename_test.c, test/meson.build, test/section_bitmaps_test.c, test/test_dwarfstring.c, test/test_extra_flag_strings.c, test/test_headersok.c, test/test_linkedtopath.c, test/testesb.c
new file:   test/meson.build
modified:   test/dwarf_tied_test.c
modified:   test/getnametest.c
modified:   test/getopttest.c
modified:   test/helpertree_test.c
modified:   test/makename_test.c
modified:   test/section_bitmaps_test.c
modified:   test/test_dwarfstring.c
modified:   test/test_extra_flag_strings.c
modified:   test/test_headersok.c
modified:   test/test_linkedtopath.c
modified:   test/testesb.c
=> Add initial meson test support

test/meson.build
modified:   ../test/meson.build
=> Fix link of test binaries on Windows

src/bin/dwarfexample/simplecrc.c, src/lib/libdwarf/dwarf_object_detector.c
modified:   src/bin/dwarfexample/simplecrc.c
modified:   src/lib/libdwarf/dwarf_object_detector.c
=> remove dump_bytes() from simplecrc.c and dwarf_object_detector.c

.github/workflows/ci_meson.yml, meson.build, meson_options.txt, src/bin/dwarfexample/dwdebuglink.c, src/bin/dwarfexample/findfuncbypc.c, src/bin/dwarfexample/frame1.c, src/bin/dwarfexample/jitreader.c, src/bin/dwarfexample/meson.build, src/bin/dwarfexample/showsectiongroups.c, src/bin/dwarfexample/simplereader.c
new file:   src/bin/dwarfexample/meson.build
modified:   .github/workflows/ci_meson.yml
modified:   meson_options.txt
modified:   src/bin/dwarfexample/dwdebuglink.c
modified:   src/bin/dwarfexample/findfuncbypc.c
modified:   src/bin/dwarfexample/frame1.c
modified:   src/bin/dwarfexample/jitreader.c
modified:   src/bin/dwarfexample/showsectiongroups.c
modified:   src/bin/dwarfexample/simplereader.c
=> Add meson support for examples

.github/workflows/ci_msys2.yml
new file:   .github/workflows/ci_msys2.yml
=> Add msys2 CI

.github/workflows/c-cpp.yml, README.md
modified:   .github/workflows/c-cpp.yml
modified:   README.md
=> Add msys2 CI badge in README.md

README.md
Also reorder badges by OS
modified:   README.md
=> Add msys2 cmake badge

src/lib/libdwarf/libdwarf_private.h
modified:   src/lib/libdwarf/libdwarf.h
=> define off_t only for microsoft compiler

CMakeLists.txt, src/lib/libdwarf/CMakeLists.txt
This PR has some changes that are useful and needed for use through FetchContent
=> Cmake improvements

src/lib/libdwarf/CMakeLists.txt
A couple small changes are needed for headers to be found reliably via `find_package`
=> Patch for includes

CMakeLists.txt
This module is included by default on all CMake versions
=> Use FindZLIB.cmake provided by CMake

CMakeLists.txt, cmake/config.h.cmake
Use the FindZSTD.cmake already included in cmake folder some commits ago
=> Use FindZSTD

src/lib/libdwarfp/dwarf_pro_die.c
modified:   src/lib/libdwarfp/dwarf_pro_die.c
=> Fix minor warning in libdwarfp

doc/meson.build
=> meson: remove deprecated behavior

CMakeLists.txt
See https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html
=> MSVC /MD(d) is MultiThreaded(Debug)**DLL**
